name: SavageBosses
version: 1.0
api-version: 1.8.8
main: tahpie.savage.savagebosses.SavageBosses
commands:
  boss:
    description: Savage Bosses
    usage: "Usage: /<command>"
permissions:
  savagebosses.bosses.manage:
    description: Allows management of bosses.
    default: op